# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SATRUST\OneDrive\Desktop\code\Runner2\ui files\apps_container_example.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 446)
        Dialog.setStyleSheet("QFrame {\n"
"    border: 2px solid white;\n"
"    min-height: 100px;\n"
"    border-radius: 10px;\n"
"}\n"
"#widget {\n"
"    min-height: 100px;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    min-height:20px;\n"
"    max-height:20px;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 12px;\n"
"    color: white;\n"
"}\n"
"#run_check {\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#run_check_2 {\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    color: #007ea6;\n"
"}\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.run_check = QtWidgets.QCheckBox(self.widget)
        self.run_check.setObjectName("run_check")
        self.horizontalLayout_2.addWidget(self.run_check)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 3, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.run_check_2 = QtWidgets.QCheckBox(self.widget_2)
        self.run_check_2.setObjectName("run_check_2")
        self.horizontalLayout_3.addWidget(self.run_check_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 1, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 1, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 2, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_2.addWidget(self.checkBox_16, 2, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 3, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Add"))
        self.pushButton_2.setText(_translate("Dialog", "Edit"))
        self.pushButton_3.setText(_translate("Dialog", "Delete"))
        self.pushButton_4.setText(_translate("Dialog", "Run"))
        self.label.setText(_translate("Dialog", "Category 1"))
        self.run_check.setText(_translate("Dialog", "Active"))
        self.checkBox.setText(_translate("Dialog", "File 1"))
        self.checkBox_2.setText(_translate("Dialog", "File 2"))
        self.checkBox_3.setText(_translate("Dialog", "File 5"))
        self.checkBox_4.setText(_translate("Dialog", "File 6"))
        self.checkBox_5.setText(_translate("Dialog", "File 3"))
        self.checkBox_6.setText(_translate("Dialog", "File 7"))
        self.checkBox_7.setText(_translate("Dialog", "File 4"))
        self.checkBox_8.setText(_translate("Dialog", "File 8"))
        self.label_2.setText(_translate("Dialog", "Category 2"))
        self.run_check_2.setText(_translate("Dialog", "Active"))
        self.checkBox_10.setText(_translate("Dialog", "File 1"))
        self.checkBox_14.setText(_translate("Dialog", "File 5"))
        self.checkBox_11.setText(_translate("Dialog", "File 2"))
        self.checkBox_15.setText(_translate("Dialog", "File 6"))
        self.checkBox_12.setText(_translate("Dialog", "File 3"))
        self.checkBox_16.setText(_translate("Dialog", "File 7"))
        self.checkBox_13.setText(_translate("Dialog", "File 4"))
        self.checkBox_17.setText(_translate("Dialog", "File 8"))
