# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SATRUST\OneDrive\Desktop\code\Runner2\ui files\delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(400, 293)
        DeleteWindow.setStyleSheet("QDialog {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DeleteWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vbox_item_container = QtWidgets.QVBoxLayout()
        self.vbox_item_container.setObjectName("vbox_item_container")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vbox_item_container.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.vbox_item_container)
        self.hbox_btn_container = QtWidgets.QHBoxLayout()
        self.hbox_btn_container.setObjectName("hbox_btn_container")
        self.btn_discard = QtWidgets.QPushButton(DeleteWindow)
        self.btn_discard.setObjectName("btn_discard")
        self.hbox_btn_container.addWidget(self.btn_discard)
        self.btn_save = QtWidgets.QPushButton(DeleteWindow)
        self.btn_save.setObjectName("btn_save")
        self.hbox_btn_container.addWidget(self.btn_save)
        self.verticalLayout_2.addLayout(self.hbox_btn_container)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "Delete Items"))
        self.btn_discard.setText(_translate("DeleteWindow", "Discard"))
        self.btn_save.setText(_translate("DeleteWindow", "Delete"))
