# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SATRUST\OneDrive\Desktop\code\Runner2\ui files\Runner2-Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Runner(object):
    def setupUi(self, Runner):
        Runner.setObjectName("Runner")
        Runner.resize(612, 531)
        Runner.setStyleSheet("#Runner {\n"
"    background-color: white;\n"
"\n"
"}")
        self.runner_main_layout = QtWidgets.QVBoxLayout(Runner)
        self.runner_main_layout.setContentsMargins(0, 0, 0, 0)
        self.runner_main_layout.setObjectName("runner_main_layout")
        self.tabWidget = QtWidgets.QTabWidget(Runner)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"    height: 30px;\n"
"    width: 100px;\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #007EA6;\n"
"    color: white;\n"
"}\n"
"\n"
" QTabWidget::pane {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.apps_tab = QtWidgets.QWidget()
        self.apps_tab.setStyleSheet("#apps_tab {\n"
"    background-color: #007EA6;\n"
"}")
        self.apps_tab.setObjectName("apps_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.apps_tab)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbox_apps_btn_container = QtWidgets.QGridLayout()
        self.gbox_apps_btn_container.setContentsMargins(15, -1, 15, -1)
        self.gbox_apps_btn_container.setObjectName("gbox_apps_btn_container")
        self.main_add_category_btn = QtWidgets.QPushButton(self.apps_tab)
        self.main_add_category_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.main_add_category_btn.setObjectName("main_add_category_btn")
        self.gbox_apps_btn_container.addWidget(self.main_add_category_btn, 0, 1, 1, 1)
        self.apps_btn_delete = QtWidgets.QPushButton(self.apps_tab)
        self.apps_btn_delete.setStyleSheet("min-width: 120px;")
        self.apps_btn_delete.setObjectName("apps_btn_delete")
        self.gbox_apps_btn_container.addWidget(self.apps_btn_delete, 0, 3, 1, 1)
        self.apps_btn_edit = QtWidgets.QPushButton(self.apps_tab)
        self.apps_btn_edit.setStyleSheet("min-width: 120px;")
        self.apps_btn_edit.setObjectName("apps_btn_edit")
        self.gbox_apps_btn_container.addWidget(self.apps_btn_edit, 0, 2, 1, 1)
        self.btn_run = QtWidgets.QPushButton(self.apps_tab)
        self.btn_run.setStyleSheet("#btn_run {\n"
"    background-color: white;\n"
"    color: #007EA6;\n"
"    border: 2px solid white;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"#btn_run:pressed {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}")
        self.btn_run.setObjectName("btn_run")
        self.gbox_apps_btn_container.addWidget(self.btn_run, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gbox_apps_btn_container.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gbox_apps_btn_container.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gbox_apps_btn_container)
        self.apps_container_vlayout = QtWidgets.QVBoxLayout()
        self.apps_container_vlayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.apps_container_vlayout.setObjectName("apps_container_vlayout")
        self.apps_scroll_area = QtWidgets.QScrollArea(self.apps_tab)
        self.apps_scroll_area.setStyleSheet("background-color: #007ea6;")
        self.apps_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.apps_scroll_area.setWidgetResizable(True)
        self.apps_scroll_area.setObjectName("apps_scroll_area")
        self.apps_scroll_area_widget = QtWidgets.QWidget()
        self.apps_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.apps_scroll_area_widget.setObjectName("apps_scroll_area_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.apps_scroll_area_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.apps_scroll_area.setWidget(self.apps_scroll_area_widget)
        self.apps_container_vlayout.addWidget(self.apps_scroll_area)
        self.verticalLayout_2.addLayout(self.apps_container_vlayout)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\SATRUST\\OneDrive\\Desktop\\code\\Runner2\\ui files\\../images/AppsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.apps_tab, icon, "")
        self.notes_tab = QtWidgets.QWidget()
        self.notes_tab.setStyleSheet("#notes_tab {\n"
"    background-color: #007EA6;\n"
"}")
        self.notes_tab.setObjectName("notes_tab")
        self.notes_tab_layout = QtWidgets.QVBoxLayout(self.notes_tab)
        self.notes_tab_layout.setContentsMargins(0, -1, 0, 0)
        self.notes_tab_layout.setObjectName("notes_tab_layout")
        self.add_note_layout = QtWidgets.QHBoxLayout()
        self.add_note_layout.setContentsMargins(15, -1, 15, -1)
        self.add_note_layout.setObjectName("add_note_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_note_layout.addItem(spacerItem2)
        self.main_add_notes_btn = QtWidgets.QPushButton(self.notes_tab)
        self.main_add_notes_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"    min-width: 170px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.main_add_notes_btn.setObjectName("main_add_notes_btn")
        self.add_note_layout.addWidget(self.main_add_notes_btn)
        self.btn_notes_edit = QtWidgets.QPushButton(self.notes_tab)
        self.btn_notes_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"    min-width: 170px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.btn_notes_edit.setObjectName("btn_notes_edit")
        self.add_note_layout.addWidget(self.btn_notes_edit)
        self.btn_notes_delete = QtWidgets.QPushButton(self.notes_tab)
        self.btn_notes_delete.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"    min-width: 170px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.btn_notes_delete.setObjectName("btn_notes_delete")
        self.add_note_layout.addWidget(self.btn_notes_delete)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_note_layout.addItem(spacerItem3)
        self.notes_tab_layout.addLayout(self.add_note_layout)
        self.notes_scroll_outer_layout = QtWidgets.QVBoxLayout()
        self.notes_scroll_outer_layout.setObjectName("notes_scroll_outer_layout")
        self.notes_scroll_area = QtWidgets.QScrollArea(self.notes_tab)
        self.notes_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.notes_scroll_area.setWidgetResizable(True)
        self.notes_scroll_area.setObjectName("notes_scroll_area")
        self.notes_scroll_area_widget = QtWidgets.QWidget()
        self.notes_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.notes_scroll_area_widget.setStyleSheet("#notes_scroll_area_widget {\n"
"    background-color: #007EA6;\n"
"}")
        self.notes_scroll_area_widget.setObjectName("notes_scroll_area_widget")
        self.notes_scroll_layout = QtWidgets.QVBoxLayout(self.notes_scroll_area_widget)
        self.notes_scroll_layout.setObjectName("notes_scroll_layout")
        self.notes_scroll_area.setWidget(self.notes_scroll_area_widget)
        self.notes_scroll_outer_layout.addWidget(self.notes_scroll_area)
        self.notes_tab_layout.addLayout(self.notes_scroll_outer_layout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\SATRUST\\OneDrive\\Desktop\\code\\Runner2\\ui files\\../images/NotesIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.notes_tab, icon1, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setStyleSheet("background-color: #007EA6;\n"
"color: white;\n"
"font-size: 16px;")
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_color = QtWidgets.QHBoxLayout()
        self.hbox_color.setObjectName("hbox_color")
        self.lbl_main_color = QtWidgets.QLabel(self.settings_tab)
        self.lbl_main_color.setObjectName("lbl_main_color")
        self.hbox_color.addWidget(self.lbl_main_color)
        self.lbl_hex_color = QtWidgets.QLabel(self.settings_tab)
        self.lbl_hex_color.setObjectName("lbl_hex_color")
        self.hbox_color.addWidget(self.lbl_hex_color)
        self.btn_choose_color = QtWidgets.QPushButton(self.settings_tab)
        self.btn_choose_color.setStyleSheet("QPushButton:pressed {\n"
"    background-color: white;\n"
"    color: #007ea6;\n"
"\n"
"}")
        self.btn_choose_color.setObjectName("btn_choose_color")
        self.hbox_color.addWidget(self.btn_choose_color)
        self.verticalLayout.addLayout(self.hbox_color)
        self.line1 = QtWidgets.QFrame(self.settings_tab)
        self.line1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.verticalLayout.addWidget(self.line1)
        self.hbox_font = QtWidgets.QHBoxLayout()
        self.hbox_font.setObjectName("hbox_font")
        self.lbl_font = QtWidgets.QLabel(self.settings_tab)
        self.lbl_font.setObjectName("lbl_font")
        self.hbox_font.addWidget(self.lbl_font)
        self.lbl_font_example = QtWidgets.QLabel(self.settings_tab)
        self.lbl_font_example.setObjectName("lbl_font_example")
        self.hbox_font.addWidget(self.lbl_font_example)
        self.cmb_font = QtWidgets.QComboBox(self.settings_tab)
        self.cmb_font.setStyleSheet("QComboBox {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    padding: 5;\n"
"  \n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    selection-background-color: #007ea6;\n"
"    background-color: white;\n"
"    color: black;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}")
        self.cmb_font.setFrame(True)
        self.cmb_font.setObjectName("cmb_font")
        self.hbox_font.addWidget(self.cmb_font)
        self.verticalLayout.addLayout(self.hbox_font)
        self.widget_order = QtWidgets.QWidget(self.settings_tab)
        self.widget_order.setObjectName("widget_order")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_order)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line2 = QtWidgets.QFrame(self.widget_order)
        self.line2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setObjectName("line2")
        self.verticalLayout_5.addWidget(self.line2)
        self.lbl_order = QtWidgets.QLabel(self.widget_order)
        self.lbl_order.setObjectName("lbl_order")
        self.verticalLayout_5.addWidget(self.lbl_order)
        self.hbox_order = QtWidgets.QHBoxLayout()
        self.hbox_order.setObjectName("hbox_order")
        self.rbtn_date = QtWidgets.QRadioButton(self.widget_order)
        self.rbtn_date.setObjectName("rbtn_date")
        self.hbox_order.addWidget(self.rbtn_date)
        self.rbtn_title = QtWidgets.QRadioButton(self.widget_order)
        self.rbtn_title.setObjectName("rbtn_title")
        self.hbox_order.addWidget(self.rbtn_title)
        self.rbtn_priority = QtWidgets.QRadioButton(self.widget_order)
        self.rbtn_priority.setObjectName("rbtn_priority")
        self.hbox_order.addWidget(self.rbtn_priority)
        self.verticalLayout_5.addLayout(self.hbox_order)
        self.verticalLayout.addWidget(self.widget_order)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.hbox_save = QtWidgets.QHBoxLayout()
        self.hbox_save.setObjectName("hbox_save")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_save.addItem(spacerItem5)
        self.btn_save = QtWidgets.QPushButton(self.settings_tab)
        self.btn_save.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_save.setStyleSheet("QPushButton:pressed {\n"
"    background-color: white;\n"
"    color: #007ea6;\n"
"\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.hbox_save.addWidget(self.btn_save)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_save.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.hbox_save)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\SATRUST\\OneDrive\\Desktop\\code\\Runner2\\ui files\\../images/SettingsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.settings_tab, icon2, "")
        self.runner_main_layout.addWidget(self.tabWidget)

        self.retranslateUi(Runner)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Runner)

    def retranslateUi(self, Runner):
        _translate = QtCore.QCoreApplication.translate
        Runner.setWindowTitle(_translate("Runner", "WorkMate"))
        self.main_add_category_btn.setText(_translate("Runner", "Add Category"))
        self.apps_btn_delete.setText(_translate("Runner", "Delete Category"))
        self.apps_btn_edit.setText(_translate("Runner", "Edit Category"))
        self.btn_run.setText(_translate("Runner", "Run Active"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps_tab), _translate("Runner", "Apps"))
        self.main_add_notes_btn.setText(_translate("Runner", "Add Notes"))
        self.btn_notes_edit.setText(_translate("Runner", "Edit Notes"))
        self.btn_notes_delete.setText(_translate("Runner", "Delete Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notes_tab), _translate("Runner", "Notes"))
        self.lbl_main_color.setText(_translate("Runner", "Main Color:"))
        self.lbl_hex_color.setText(_translate("Runner", "#007EA6"))
        self.btn_choose_color.setText(_translate("Runner", "Choose Color"))
        self.lbl_font.setText(_translate("Runner", "Font:"))
        self.lbl_font_example.setText(_translate("Runner", "This Is Your Font"))
        self.lbl_order.setText(_translate("Runner", "Order Notes By"))
        self.rbtn_date.setText(_translate("Runner", "Date"))
        self.rbtn_title.setText(_translate("Runner", "Title"))
        self.rbtn_priority.setText(_translate("Runner", "Priority"))
        self.btn_save.setText(_translate("Runner", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("Runner", "Settings"))
