# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SATRUST\OneDrive\Desktop\code\Runner2\ui files\select_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWindow(object):
    def setupUi(self, SelectWindow):
        SelectWindow.setObjectName("SelectWindow")
        SelectWindow.resize(400, 275)
        SelectWindow.setStyleSheet("QDialog {\n"
"    background-color: #007ea6;\n"
"}\n"
"\n"
"")
        self.SelectNoteLayout = QtWidgets.QVBoxLayout(SelectWindow)
        self.SelectNoteLayout.setContentsMargins(0, 0, 0, 0)
        self.SelectNoteLayout.setSpacing(0)
        self.SelectNoteLayout.setObjectName("SelectNoteLayout")
        self.scrl_area_select_notes = QtWidgets.QScrollArea(SelectWindow)
        self.scrl_area_select_notes.setStyleSheet("background-color: #007ea6;")
        self.scrl_area_select_notes.setWidgetResizable(True)
        self.scrl_area_select_notes.setObjectName("scrl_area_select_notes")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 273))
        self.scrollAreaWidgetContents.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007ea6;\n"
"    background-color: white;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.vbox_scroll_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.vbox_scroll_layout.setContentsMargins(30, -1, 30, -1)
        self.vbox_scroll_layout.setObjectName("vbox_scroll_layout")
        self.scrl_area_select_notes.setWidget(self.scrollAreaWidgetContents)
        self.SelectNoteLayout.addWidget(self.scrl_area_select_notes)

        self.retranslateUi(SelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectWindow)

    def retranslateUi(self, SelectWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectWindow.setWindowTitle(_translate("SelectWindow", "Select Notes"))
