# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add Category.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_category(object):
    def setupUi(self, add_category):
        add_category.setObjectName("add_category")
        add_category.setEnabled(True)
        add_category.resize(552, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_category.sizePolicy().hasHeightForWidth())
        add_category.setSizePolicy(sizePolicy)
        add_category.setMaximumSize(QtCore.QSize(16777215, 423))
        add_category.setFocusPolicy(QtCore.Qt.ClickFocus)
        add_category.setStyleSheet("#add_category {\n"
"    background-color: #007EA6;\n"
"\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(add_category)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_category_name = QtWidgets.QLabel(add_category)
        self.add_category_name.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.add_category_name.setObjectName("add_category_name")
        self.horizontalLayout.addWidget(self.add_category_name)
        self.add_category_name_input = QtWidgets.QLineEdit(add_category)
        self.add_category_name_input.setStyleSheet("font-size: 16px;\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.add_category_name_input.setObjectName("add_category_name_input")
        self.horizontalLayout.addWidget(self.add_category_name_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_category_add_file_btn = QtWidgets.QPushButton(add_category)
        self.add_category_add_file_btn.setObjectName("add_category_add_file_btn")
        self.horizontalLayout_2.addWidget(self.add_category_add_file_btn)
        self.add_category_add_url_btn = QtWidgets.QPushButton(add_category)
        self.add_category_add_url_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.add_category_add_url_btn.setObjectName("add_category_add_url_btn")
        self.horizontalLayout_2.addWidget(self.add_category_add_url_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.apps_container_vl = QtWidgets.QVBoxLayout()
        self.apps_container_vl.setObjectName("apps_container_vl")
        self.verticalLayout.addLayout(self.apps_container_vl)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_category_discard_btn = QtWidgets.QPushButton(add_category)
        self.add_category_discard_btn.setObjectName("add_category_discard_btn")
        self.horizontalLayout_3.addWidget(self.add_category_discard_btn)
        self.add_category_save_btn = QtWidgets.QPushButton(add_category)
        self.add_category_save_btn.setObjectName("add_category_save_btn")
        self.horizontalLayout_3.addWidget(self.add_category_save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(add_category)
        QtCore.QMetaObject.connectSlotsByName(add_category)

    def retranslateUi(self, add_category):
        _translate = QtCore.QCoreApplication.translate
        add_category.setWindowTitle(_translate("add_category", "Add Category"))
        self.add_category_name.setText(_translate("add_category", "Name"))
        self.add_category_add_file_btn.setText(_translate("add_category", "Add File"))
        self.add_category_add_url_btn.setText(_translate("add_category", "Add URL"))
        self.add_category_discard_btn.setText(_translate("add_category", "Discard"))
        self.add_category_save_btn.setText(_translate("add_category", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_category = QtWidgets.QDialog()
    ui = Ui_add_category()
    ui.setupUi(add_category)
    add_category.show()
    sys.exit(app.exec_())
