# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Runner2-Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Runner(object):
    def setupUi(self, Runner):
        Runner.setObjectName("Runner")
        
        Runner.resize(656, 531)
        Runner.setStyleSheet("#Runner {\n"
"    background-color: white;\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Runner)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Runner)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
"    background-color: #007EA6;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"    height: 30px;\n"
"    width: 100px;\n"
"    color: #007EA6;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #007EA6;\n"
"    color: white;\n"
"}\n"
"\n"
" QTabWidget::pane {\n"
"    background-color: #007EA6;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.apps_tab = QtWidgets.QWidget()
        self.apps_tab.setStyleSheet("#apps_tab {\n"
"    background-color: #007EA6;\n"
"}")
        self.apps_tab.setObjectName("apps_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.apps_tab)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_apps_btn_hlayout = QtWidgets.QHBoxLayout()
        self.add_apps_btn_hlayout.setContentsMargins(15, -1, 15, -1)
        self.add_apps_btn_hlayout.setObjectName("add_apps_btn_hlayout")
        self.main_add_category_btn = QtWidgets.QPushButton(self.apps_tab)
        self.main_add_category_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.main_add_category_btn.setObjectName("main_add_category_btn")
        self.add_apps_btn_hlayout.addWidget(self.main_add_category_btn)
        self.verticalLayout_2.addLayout(self.add_apps_btn_hlayout)
        self.apps_container_vlayout = QtWidgets.QVBoxLayout()
        self.apps_container_vlayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.apps_container_vlayout.setObjectName("apps_container_vlayout")
        self.apps_scroll_area = QtWidgets.QScrollArea(self.apps_tab)
        self.apps_scroll_area.setStyleSheet("QScrollArea {\n"
"    background-color: #007EA6;\n"
"}")
        self.apps_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.apps_scroll_area.setWidgetResizable(True)
        self.apps_scroll_area.setObjectName("apps_scroll_area")
        self.apps_scroll_area_widget = QtWidgets.QWidget()
        self.apps_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 654, 449))
        self.apps_scroll_area_widget.setStyleSheet("#apps_scroll_area_widget {\n"
"    background-color: #007EA6;\n"
"}")
        self.apps_scroll_area_widget.setObjectName("apps_scroll_area_widget")
        self.apps_scroll_area.setWidget(self.apps_scroll_area_widget)
        self.apps_container_vlayout.addWidget(self.apps_scroll_area)
        self.verticalLayout_2.addLayout(self.apps_container_vlayout)
        self.tabWidget.addTab(self.apps_tab, "")
        self.notes_tab = QtWidgets.QWidget()
        self.notes_tab.setStyleSheet("#notes_tab {\n"
"    background-color: #007EA6;\n"
"}")
        self.notes_tab.setObjectName("notes_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.notes_tab)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_add_notes_btn = QtWidgets.QPushButton(self.notes_tab)
        self.main_add_notes_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #007EA6;\n"
"    background-color: white;\n"
"    border-color: #007EA6;\n"
"}")
        self.main_add_notes_btn.setObjectName("main_add_notes_btn")
        self.horizontalLayout.addWidget(self.main_add_notes_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.notes_tab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.notes_scroll_area_widget = QtWidgets.QWidget()
        self.notes_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 654, 449))
        self.notes_scroll_area_widget.setStyleSheet("#notes_scroll_area_widget {\n"
"    background-color: #007EA6;\n"
"}")
        self.notes_scroll_area_widget.setObjectName("notes_scroll_area_widget")
        self.scrollArea.setWidget(self.notes_scroll_area_widget)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.notes_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Runner)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Runner)

    def retranslateUi(self, Runner):
        _translate = QtCore.QCoreApplication.translate
        Runner.setWindowTitle(_translate("Runner", "Runner"))
        self.main_add_category_btn.setText(_translate("Runner", "Add catergory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps_tab), _translate("Runner", "Apps"))
        self.main_add_notes_btn.setText(_translate("Runner", "Add Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notes_tab), _translate("Runner", "Notes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Runner = QtWidgets.QWidget()
    ui = Ui_Runner()
    ui.setupUi(Runner)
    Runner.show()
    sys.exit(app.exec_())
